baseURL = "https://miketeachestech.com.au"
title = "Mike Teaches Tech"
author = "Michael"
languageCode = "en-AU"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true
googleAnalytics = "G-3XWV234E74"

[params]
  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Mike Teaches Tech Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    # size = "h-14"

  [params.site]
    name = "Mike Teaches Tech"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Mike Teaches Tech provides high quality in-home tech support, tutoring services, and workshops for schools/groups."
    meta_og_title = "Mike Teaches Tech"
    meta_og_type = "website"
    meta_og_url = "https://miketeachestech.com"
    meta_og_image = "img/logo/logo.png"
    meta_og_description = "Mike Teaches Tech provides high quality in-home tech support, tutoring services, and workshops for schools/groups."

[menu]

  [[menu.main]]
    identifier = "hsc-software-engineering-tutoring"
    name = "Tutoring"
    url = "/hsc-software-engineering-tutoring"
    weight = 1

  [[menu.main]]
      identifier = "tech-support-inner-west-sydney"
      name = "Tech Support"
      url = "/tech-support-inner-west-sydney"
      weight = 2

  [[menu.main]]
    identifier = "workshops-for-schools-sydney-nsw"
    name = "Workshops"
    url = "/workshops-for-schools-sydney-nsw"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About Mike"
    url = "/about"
    weight = 4

  [[menu.main]]
    identifier = "blog"
    name = "Posts & Notices"
    url = "/blog/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/miketeachestech"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2

  [[menu.footer]]
    name = "YouTube"
    url = "https://www.youtube.com/@miketeachestech-au"
    pre = "<i class='icon-youtube text-2xl'></i>"
      weight = 3