baseURL = "https://miketeachestech.com"
title = "Mike Teaches Tech"
author = "Michael"
languageCode = "en-AU"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true
#googleAnalytics = "to be added"

[params]

  showBlog = true
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "Tella Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "Mike Teaches Tech"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_og_title = "Tella"
    meta_og_type = "website"
    meta_og_url = "https://tella.pages.dev"
    meta_og_image = "https://raw.githubusercontent.com/opera7133/tella/master/images/tn.png"
    meta_og_description = "A Hugo Theme for OSSProject, Companies, Organization..."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "tech-support-inner-west-sydney"
    name = "Tech Support"
    url = "/tech-support-inner-west-sydney/"
    weight = 1

  [[menu.main]]
    identifier = "hsc-software-engineering-tutoring"
    name = "Tutoring"
    url = "/hsc-software-engineering-tutoring/"
    weight = 2

  [[menu.main]]
    identifier = "workshops-for-schools-sydney-nsw"
    name = "Workshops"
    url = "/workshops-for-schools-sydney-nsw/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "About Mike"
    url = "/about/"
    weight = 4

  [[menu.main]]
    identifier = "blog"
    name = "Posts & Notices"
    url = "/blog/"
    weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/opera7133/tella"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 2
